server:
  port: 8007
  
spring:
  cloud:
    gateway:
      routes:
      #Route Mapping
      - id: product-service               #RouteIdentifiler
        uri: http://localhost:8011/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/product/**
      - id: profile-service               #RouteIdentifiler
        uri: http://localhost:8002/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /userprofile/** 
      - id: cart-service               #RouteIdentifiler
        uri: http://localhost:8009/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/cartsystem/** 
      - id: order-service               #RouteIdentifiler
        uri: http://localhost:8010/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/order/** 
                              